### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by LauLauThom** [bdgp/OpenHiCAMM#35]
Hello,
Do you have a step-by-step guide of how to install OpenHiCAMM for Windows ? 
I tried to add `http://fruitfly.org/openhicamm` as an update site to my Fiji installation but it is not recognised (`Error : not in a gzip format`). 
Thanks

**Comment by benwbooth** [comment]
Hi @Jindil 
You need to add the appropriate subdirectory for your version of windows, e.g. 32 vs 64 bit. Most modern Windows installations are 64-bit, so you probably want to add this URL:

https://fruitfly.org/openhicamm/micromanager-win64/

Please note that the packages in the Fiji repository are 3 years out-of-date. You might consider building OpenHiCAMM from source and installing the module into your Fiji/Micro-Manager installation if you wish to use the most recent version.

OpenHiCAMM in its current state is really more of a framework and a database model for automated imaging, and not so much a polished product. The workflow code that comes with it is geared toward the automated imaging of Drosophila embryos, although that doesn't preclude someone with a working knowledge of Java and ImageJ from creating their own workflows. You may be able to get by with the available modules already written for image acquisition and processing, or you may need to write custom modules in Java to implement the functionality you need.

Getting the most out of OpenHiCAMM requires the use of an automated slide loader and accompanying OpenHiCAMM driver module. Unfortunately the Slide Loader we have been using in-house uses closed source C++ driver code which the vendor does not allow us to distribute. So anyone wanting to use OpenHiCAMM will have to either manually load slides or write their own OpenHiCAMM module for their specific automated slide loader. Hope this helps!
